### ISSUE TITLE
Is it possible to use list of files from server instead of drag and drop?

### ISSUE THREAD

**Issue by jeyarajcs** [ivmartel/dwv-react#33]
This is not an issue. 
Just I want to know, is there any possibility to use remote server which has list of dicom files to show at the UI.

Currently it gives Drag and Drop files. Instead of that I need to give files through URL. Kindly let me know is there any possibility to do that.

**Comment by ivmartel** [comment]
Yes you can! Check out the dwv wiki: [User-Stories#io](https://github.com/ivmartel/dwv/wiki/User-Stories#io)

**Comment by ivmartel** [comment]
I hope I answered your question. Feel free to comment if you need.

**Comment by zuesmano** [comment]
Hi, i tried to use the way you have mentioned but it is not working through the url. 

> https://ivmartel.github.io/dwv-react/demo/stable/index.html?input=https://raw.githubusercontent.com/ivmartel/dwv/master/tests/data/?file=bbmri-53323851.dcm&file=bbmri-53323707.dcm&file=bbmri-53323563.dcm&file=bbmri-53323419.dcm&file=bbmri-53323275.dcm&file=bbmri-53323131.dcm&dwvReplaceMode=void
<

this link just opens the viewer but does not show any file.

**Comment by ivmartel** [comment]
You need to (urlencode)[https://en.wikipedia.org/wiki/Percent-encoding] the url of the DICOM file otherwise its special characters get mixed with the root one. 

In you case:
`https://raw.githubusercontent.com/ivmartel/dwv/master/tests/data/?file=bbmri-53323851.dcm&file=bbmri-53323707.dcm&file=bbmri-53323563.dcm&file=bbmri-53323419.dcm&file=bbmri-53323275.dcm&file=bbmri-53323131.dcm`

Becomes:
`https%3A%2F%2Fraw.githubusercontent.com%2Fivmartel%2Fdwv%2Fmaster%2Ftests%2Fdata%2F%3Ffile%3Dbbmri-53323851.dcm%26file%3Dbbmri-53323707.dcm%26file%3Dbbmri-53323563.dcm%26file%3Dbbmri-53323419.dcm%26file%3Dbbmri-53323275.dcm%26file%3Dbbmri-53323131.dcm`

So the final url is: https://ivmartel.github.io/dwv-react/demo/stable/index.html?input=https%3A%2F%2Fraw.githubusercontent.com%2Fivmartel%2Fdwv%2Fmaster%2Ftests%2Fdata%2F%3Ffile%3Dbbmri-53323851.dcm%26file%3Dbbmri-53323707.dcm%26file%3Dbbmri-53323563.dcm%26file%3Dbbmri-53323419.dcm%26file%3Dbbmri-53323275.dcm%26file%3Dbbmri-53323131.dcm&dwvReplaceMode=void
